# Generated by Django 3.2.12 on 2022-02-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailserveradmin', '0004_auto_20220207_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maildomain',
            options={'ordering': ['name'], 'permissions': [('add_mailuser', 'Can add a user to this domain'), ('add_mailalias', 'Can add an alias to this domain')]},
        ),
    ]
